# Generated by Django 2.2.7 on 2019-11-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=20)),
                ('mem_age', models.IntegerField()),
                ('mem_email', models.CharField(max_length=20)),
            ],
        ),
    ]
